Heatmap: Implementation of color theme
ruchika-narang/observability pull request #2
Opened 2022-05-27 12:08 UTC by ruchika-narang

### Description
Implementation of color theme for heatmap

2022-06-01 10:17 UTC, abasatwar requested changes

2022-06-01 10:17 UTC, abasatwar commented on dashboards-observability/common/constants/colors.ts
> +    value: RdBu_PALETTE.name,
can be renamed as `redBlue_PALETTE`.

2022-06-01 10:17 UTC, abasatwar commented on dashboards-observability/common/constants/colors.ts
> +export const RdBu_PALETTE = {
can we `RdBu_PALETTE` as `RedBlue_PALETTE`?

2022-06-01 10:17 UTC, abasatwar commented on dashboards-observability/common/constants/colors.ts
> +export const YlGnBu_PALETTE = {
same as above.

2022-06-01 10:17 UTC, abasatwar commented on dashboards-observability/common/constants/colors.ts
> +export const DEFAULT_PALETTE = 'default';
keep this constant at same place in all PRs. This was present in treemap PR. So we can avoid having multiple constants with same name.

2022-06-01 10:17 UTC, abasatwar commented on dashboards-observability/common/constants/colors.ts
> +    value: YlOrRd_PALETTE.name,
check the names if we can rename.

2022-06-01 10:17 UTC, abasatwar commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/config_heatmap_color_palette_picker.tsx
> +  console.log(selectedColor, 'selectedColor');
please remove console.

2022-06-01 10:17 UTC, abasatwar commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/config_heatmap_color_palette_picker.tsx
> +    onSelectChange(getColorObject(value));
`onSelectChange({ name, color: name})` can be used.

2022-06-01 10:17 UTC, abasatwar commented on dashboards-observability/public/components/event_analytics/utils/utils.tsx
> +export const lightenColor = (color: string, percent: number) => {
eslint suppressor is not required?

2022-06-01 12:46 UTC, ruchika-narang commented on dashboards-observability/common/constants/colors.ts
> +export const DEFAULT_PALETTE = 'default';
It's already on the same line as Treemap.

2022-06-01 12:47 UTC, ruchika-narang commented on dashboards-observability/public/components/event_analytics/utils/utils.tsx
> +export const lightenColor = (color: string, percent: number) => {
The eslint suppressor is present for the whole file, kindly check the first line of this file.

2022-06-02 09:27 UTC, abasatwar approved these changes

2022-06-02 10:20 UTC, closed without merging